---
apiVersion: v2
name: plausible-analytics
description: A Helm Chart for Plausible Analytics - Simple, open-source, lightweight (< 1 KB) and privacy-friendly web analytics alternative to Google Analytics.
type: application
version: 0.3.4
appVersion: 3.0.1
keywords:
  - web analytics
  - analytics
  - plausible
sources:
  - https://github.com/plausible/analytics
  - https://github.com/imio/helm-charts
  - https://github.com/imio/helm-plausible-analytics
icon: https://plausible.io/uploads/plausible-community-edition.png
maintainers:
  - name: IMIO
    url: https://github.com/IMIO/
dependencies:
  - name: postgresql
    alias: postgresql
    version: 16.6.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: clickhouse
    alias: clickhouse
    version: 7.2.0
    repository: https://charts.bitnami.com/bitnami
    condition: clickhouse.enabled
