apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plausible-analytics.fullname" . }}
  labels:
    {{- include "plausible-analytics.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "plausible-analytics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plausible-analytics.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plausible-analytics.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-db
          image: postgres:13.3-alpine
          command: ['sh', '-c', 'until pg_isready -h {{ .Values.postgresql.host }} -p {{ .Values.postgresql.port }} -U {{ .Values.postgresql.auth.username }}; do echo "Waiting for PostgreSQL to be ready..."; sleep 2; done;']
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -x
            - -c
            - /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin
            #- /entrypoint.sh db createdb && /entrypoint.sh plausible_events_db clickhouse-client --host {{ .Values.clickhouse.host }} --query "CREATE DATABASE IF NOT EXISTS plausible_events_db"  && /entrypoint.sh db migrate && /entrypoint.sh db init-admin
          env:
            {{- if .Values.baseURL }}
            - name: BASE_URL
              value: {{ .Values.baseURL | toString | quote }}
            {{- end }}
            {{- if .Values.service.port }}
            - name: PORT
              value: {{ .Values.service.port | toString | quote }}
            {{- end }}
            {{- if .Values.listenip }}
            - name: LISTEN_IP
              value: {{ .Values.listenip | toString | quote }}
            {{- end }}
            {{- if .Values.adminUser.email }}
            - name: ADMIN_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  key: ADMIN_USER_EMAIL
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.adminUser.email }}
            - name: ADMIN_USER_NAME
              valueFrom:
                secretKeyRef:
                  key: ADMIN_USER_NAME
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.adminUser.email }}
            - name: ADMIN_USER_PWD
              valueFrom:
                secretKeyRef:
                  key: ADMIN_USER_PWD
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.postgresql.enabled }}
            {{- if .Values.postgresql.url }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: DATABASE_URL
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- end }}
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  key: SECRET_KEY_BASE
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- if .Values.clickhouse.enabled }}
            {{- if .Values.clickhouse.url }}
            - name: CLICKHOUSE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: CLICKHOUSE_DATABASE_URL
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  key: CLICKHOUSE_USER
                  name: {{ include "plausible-analytics.fullname" . }}
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: CLICKHOUSE_PASSWORD
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.smtp.enabled }}
            {{- if .Values.smtp.mailer.emailAddress }}
            - name: MAILER_EMAIL
              valueFrom:
                secretKeyRef:
                  key: MAILER_EMAIL
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.smtp.adapter }}
            - name: MAILER_ADAPTER
              valueFrom:
                secretKeyRef:
                  key: MAILER_ADAPTER
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.smtp.host }}
            - name: SMTP_HOST_ADDR
              valueFrom:
                secretKeyRef:
                  key: SMTP_HOST_ADDR
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.smtp.port }}
            - name: SMTP_HOST_PORT
              valueFrom:
                secretKeyRef:
                  key: SMTP_HOST_PORT
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.smtp.username }}
            - name: SMTP_USER_NAME
              valueFrom:
                secretKeyRef:
                  key: SMTP_USER_NAME
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.smtp.password }}
            - name: SMTP_USER_PWD
              valueFrom:
                secretKeyRef:
                  key: SMTP_USER_PWD
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.smtp.ssl.enabled }}
            - name: SMTP_HOST_SSL_ENABLED
              valueFrom:
                secretKeyRef:
                  key: SMTP_HOST_SSL_ENABLED
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.smtp.retires }}
            - name: SMTP_RETRIES
              valueFrom:
                secretKeyRef:
                  key: SMTP_RETRIES
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- end }}
            {{- if .Values.google.clientID }}
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_ID
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.google.clientSecret }}
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_CLIENT_SECRET
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.twitter.consumer.key }}
            - name: TWITTER_CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  key: TWITTER_CONSUMER_KEY
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.twitter.consumer.secret }}
            - name: TWITTER_CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  key: TWITTER_CONSUMER_SECRET
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.twitter.access.token }}
            - name: TWITTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  key: TWITTER_ACCESS_TOKEN
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.twitter.access.secret }}
            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  key: TWITTER_ACCESS_TOKEN_SECRET
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.disableAuth }}
            - name: DISABLE_AUTH
              value: {{ .Values.disableAuth | toString | quote }}
            {{- end }}
            {{- if .Values.disableRegistration }}
            - name: DISABLE_REGISTRATION
              value: {{ .Values.disableRegistration | toString | quote }}
            {{- end }}
            {{- if .Values.logFailedLoginAttempts }}
            - name: LOG_FAILED_LOGIN_ATTEMPTS
              value: {{ .Values.logFailedLoginAttempts | toString | quote }}
            {{- end }}
#            {{- if .Values.geolocation.enabled }}
#            - name: GEOLITE2_COUNTRY_DB
#              value: "/geoip/GeoLite2-Country.mmdb"
#            {{ end }}
            {{- if .Values.postmark.apiKey }}
            - name: POSTMARK_API_KEY
              valueFrom:
                secretKeyRef:
                  key: POSTMARK_API_KEY
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
            {{- if .Values.geoliteCountryDB }}
            - name: GEOLITE2_COUNTRY_DB
              valueFrom:
                secretKeyRef:
                  key: GEOLITE2_COUNTRY_DB
                  name: {{ include "plausible-analytics.fullname" . }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
