name: Helm Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Publish Helm chart
        uses: tylerauerbeck/helm-gh-pages@main
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          charts_dir: .
          charts_url: https://imio.github.io/helm-charts/
          owner: IMIO
          repository: helm-charts
          branch: gh-pages
          target_dir: .
          dependencies: bitnami,https://charts.bitnami.com/bitnami
