---
name: Lint and Test Charts

on: [push, workflow_dispatch]

jobs:
  lint-test:
    runs-on:
      group: self-hosted
    steps:
      - name: Lint and Test Charts
        uses: IMIO/gha/helm-test-notify@v3.9.2
        with:
          HELM_RELEASE: plausible-analytics
          HELM_NAMESPACE: plausible-analytics
          MATTERMOST_WEBHOOK_URL: ${{ secrets.COMMON_MATTERMOST_WEBHOOK_URL }}
